# Generated by Django 3.0.4 on 2020-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200507_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dönem Notu'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Firma Notu'),
        ),
        migrations.AddField(
            model_name='budget',
            name='group_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Grup Notu'),
        ),
    ]
