# Generated by Django 3.0.4 on 2020-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200508_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dönem Notu:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='company_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Firma Notu:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Varsa Mali Döneme İlişkin Dosya Ekleyin:'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='group_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Grup Notu:'),
        ),
    ]
