# Generated by Django 3.0.4 on 2020-05-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200508_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_rate',
            new_name='rate',
        ),
    ]
