# Generated by Django 3.0.4 on 2020-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200508_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='L690',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='691 Dönem Karı Vergi ve Diğer Yas. Yük. Karş.'),
        ),
    ]
