# Generated by Django 3.0.4 on 2020-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200528_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['user', '-period', '-saving_date', 'tax_title', 'id']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='L100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='100 Kasa'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L101',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='101 Alınan Çekler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L102',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='102 Bankalar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L103',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='103 Verilen Çekler ve Ödeme Emirleri (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L108',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='108 Diğer Hazır Değerler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L110',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='110 Hisse Senetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L111',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='111 Özel Kesim Tahvil, Senet ve Bonoları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L112',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='112 Kamu Kesim Tahvil, Senet ve Bonoları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L118',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='118 Diğer Menkul Kıymetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L119',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='119 Menkul Kıymetler Değ. Düş. Karş.(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L1201',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='120-01 Yurtiçi Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L1202',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='120-02 Yurtdışı Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L1203',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='120-03 Alacak Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L121',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='121 Alacak Senetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L122',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='122 Alacak Senetleri Reeskontu'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L126',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='126 Verilen Depozito ve teminatlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L127',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='127 Diğer Ticari Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L128',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='128 Şüpheli Ticari Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L129',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='129 Şüpheli Ticari Alacak Karşılığı (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L131',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='131 Ortaklardan Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L132',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='132 İştiraklarden Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L133',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='133 Bağlı Ortaklıklardan Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L135',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='135 Personelden Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L136',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='136 Diğer Çeşitli Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L137',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='137 Diğer Alacak Senetleri Reeskontu (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L138',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='138 Şüpheli Diğer Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L139',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='139 Şüpheli Diğer Alacaklar Karşılığı (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L150',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='150 İlk Madde ve Malzeme'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L151',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='151 Yarı Mamuller Üretim'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L152',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='152 Mamullar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L153',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='153 Ticari Mallar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L157',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='157 Diğer Stoklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L158',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='158 Stok Değer Düşük Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L159',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='159 Verilen Sipariş Avansları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L170',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='170 Yıllara Yaygın İnş. ve Onarım Maliyetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L171',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='171 Taşeronlara Verilen Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L178',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='178 Yıllara Yaygın İnş. Enf. Düzeltmeleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L180',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='180 Gelecek Aylara Ait Giderler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L181',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='181 Gelir Tahakkukları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L190',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='190 Devreden KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L191',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='191 İndirilecek KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L192',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='192 Diğer KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L193',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='193 Peşin Ödenen Vergiler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L194',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='194 Ertelenen Vergi Varlıkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L195',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='195 İş Avansları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L196',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='196 Personel Avansları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L197',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='197 Sayım ve Tesellüm Noksanları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L198',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='198 Diğer Çeşitli Dönen Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L199',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='199 Diğer Dönen Varlıklar Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L200',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='200 Yıllara Yaygın İnş. ve Onarım Maliyetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L201',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='201 Taşeronlara Verilen Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L210',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='210 Leasing İle Alınan Sabit Kıymetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L211',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='211 Birikmiş Amortismanlar (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L2201',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='220-1 UV Ticari Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L2202',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='220-2 Alacak Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L221',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='221 Alacak Senetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L222',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='222 Alacak Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L226',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='226 Verilen Depozito ve Teminatlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L228',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='228 Şüpheli Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L229',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='229 Şüpheli Alacaklar Karşılığı(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L231',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='231 Ortaklardan Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L232',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='232 İstiraklerden Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L233',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='233 Bağlı Ortaklıklardan Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L235',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='235 Personelden Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L236',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='236 Diğer Çeşitli Alacaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L237',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='237 Diğer Alacak Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L239',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='239 Şüpheli Diğer Alacaklar Karşılığı(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L240',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='240 Bağlı Menkul Kıymetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L241',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='241 Bağlı Menkul Kıymet Değ. Düş. Karş.(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L242',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='242 İştirakler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L243',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='243 İştirak Sermaye Taahhütleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L244',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='244 İştirakler Ser. Pay. Değ. Düş. Karş.(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L245',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='245 Bağlı Ortaklıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L246',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='246 Bağlı Ortaklıklara Sermaye Taah.(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L247',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='247 Bağlı Ort. Ser. Pay. Değ. Düş. Karş.(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L248',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='248 Diğer Mali Duran VArlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L249',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='249 Diğer Mali Duran Varlıklar Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L250',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='250 Arazi ve Arsalar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L251',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='251 Yer Altı ve Yer Üstü Düzenleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L252',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='252 Binalar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L253',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='253 Tesis, Makina ve Cihazlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L254',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='254 Taşıtlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L255',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='255 Demirbaşlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L256',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='256 Diğer Maddi Duran Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L257',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='257 Birikmiş Amortismanlar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L258',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='258 Yapılmakta Olan Yatırımlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L259',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='259 Verilen Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L260',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='260 Haklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L261',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='261 Şerefiye'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L262',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='262 Kuruluş ve Örgütlenme Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L263',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='263 Araştırma ve Geliştirme giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L264',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='264 Özel Maliyetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L267',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='267 Diğer Maddi Olmayan Duran Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L268',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='268 Birikmiş Amortismanlar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L269',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='269 Verilen Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L271',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='271 Arama Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L272',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='272 Hazırlık ve Geliştirme Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L277',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='277 Diğer Özel Tüketime Tabi Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L278',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='278 Birikmiş Tükenme Payları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L279',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='279 Verilen Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L280',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='280 Gelecek Yıllara Ait Giderler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L281',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='281 Gelir Tahakkukları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L291',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='291 Gelecek Yıllarda İndirilecek KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L292',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='292 Diğer KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L293',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='293 Gelecek Yıllar İhtiyacı Stoklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L294',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='294 Elden Çıkarılacak Stok ve Maddi Duran Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L295',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='295 Peşin Ödenen Vergi ve Fonlar / Hakediş Stopajları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L296',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='296 Ertelenen Vergi Varlıkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L297',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='297 Diğer Çeşitli Duran Varlıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L298',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='298 Stok Değer Düşüş Karşılığı (-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L299',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='299 Birikmiş Amortismanlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L300',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='300 Bankalara Borçlar KV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L301',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='301 Finansal Kiralama Borçları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L302',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='302 Ertelenmiş Fin. Kir. Borç Maliyetleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L303',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='303 UV Kredilerin KV Taksitleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L304',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='304 Tahvil Anapara Borç, Taksit ve Faiz'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L305',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='305 Çıkarılmış Bono ve Senetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L306',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='306 Çıkarılmış Diğer Menkul Kıymetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L308',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='308 Menkul Kıymetler İhraç Farkı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L309',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='309 Diğer Mali Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L3201',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='320-1 Yurtiçine Boçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L3202',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='320-2 Yurtdışına Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L321',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='321 Borç Senetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L322',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='322 Borç Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L326',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='326 Alınan Depozito ve Teminatlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L329',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='329 Diğer Ticari Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L331',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='331 Ortaklara Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L332',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='332 İştiraklere Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L333',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='333 Bağlı Ortaklıklara Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L335',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='335 Personele Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L336',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='336 Diğer Çeşitli Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L337',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='337 Diğer Borç Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L338',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='338 Dağıtılacak Kar Payları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L340',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='340 Alınan Sipariş Avansları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L349',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='349 Alınan Diğer Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L350',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='350 Yıllara Yaygın İnş. ve Onarım Hakedişleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L351',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='351 Taahhüt Avansı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L358',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='358 Yıllara Yaygın İnş. Enf. Düz. Hesabı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L360',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='360 Ödenecek Vergi ve Fonlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L361',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='361 Ödenecek Sosyal Güvenli Kesintileri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L368',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='368 Vadesi Geçmiş Ert. veya Taks. Vergi ve Diğer'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L369',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='369 Ödenecek Diğer Yükümlülükler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L370',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='370 Dönem Karı Vergi ve Diğer Yasal Yük. Karş.'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L371',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='371 Peşin Ödenen Vergi ve Fonlar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L372',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='372 Kıdem Tazminatı Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L373',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='373 Maliyet Giderleri Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L379',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='379 Diğer Borç ve Gider Karşılıkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L380',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='380 Gelecek Aylara Ait Gelirler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L381',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='381 Gider Tahakkukları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L391',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='391 Hesaplanan KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L392',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='392 Diğer KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L393',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='393 Merkez ve Şubeler Cari Hesabı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L394',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='394 Ertelenen Vergi Yükümlülükleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L397',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='397 Satım ve Tesellüm Fazlaları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L399',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='399 Diğer Çeşitli YAbancı Kaynaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L400',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='400 Banka Kredileri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L401',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='401 Finansal Kiralama Borçları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L402',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='402 Ertelenmiş Fin. Kir. Borç. Maliyetleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L405',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='405 Çıkarılmış Tahviller'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L407',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='407 Çıkarılmış Diğer Menkul Kıymetler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L408',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='408 Menkul Kıymetler İhraç Farkı(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L409',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='409 Diğer Mali Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L410',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='410 Yıllara Yaygın İnşaat ve Onarım Hakedişleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L420',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='420 Satıcılar (UV)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L421',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='421 Borç Senetleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L422',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='422 Borç Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L426',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='426 Alınan Depozito ve Teminatlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L429',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='429 Diğer Ticari Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L431',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='431 Ortaklara Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L432',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='432 İştiraklere Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L433',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='433 Bağlı Ortaklıklara Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L436',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='436 Diğer Çeşitli Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L437',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='437 Diğer Borç Senetleri Reeskontu(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L438',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='438 Kamuya Olan Ert. Taks. Borçlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L440',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='440 Alınan Sipariş Avansları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L449',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='449 Alınan Diğer Avanslar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L472',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='472 Kıdem Tazminatı Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L479',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='479 Diğer Borç ve Gider Karşılıkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L480',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='480 Gelecek Yıllara Ait Gelirler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L481',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='481 Gider Tahakkukları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L492',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='492 Gelecek Yıllara Ertelenen veya Terkin Edilen KDV'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L493',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='493 Tesise Katılma Payları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L496',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='496 Ertelenen Vergi Yükümlülükleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L499',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='499 Diğer Çeşitli UV Yabancı Kaynaklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L500',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='500 Sermaye'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L501',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='501 Ödenmemiş Sermaye(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L502',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='502 Sermaye Düzeltmesi Olumlu Farkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L503',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='503 Sermaye Düzeltmesi Olumsuz Farkları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L520',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='520 Hisse Senetleri İhraç Pirimleri (Emisyon Pirimi)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L521',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='521 Hisse Senedi İptal Kararları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L522',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='522 Maddi Duran Varlık Yeniden Değ. Artışları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L523',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='523 İstirakler Yeniden Değerleme Artışları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L525',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='525 Kayda Alınan Emtia Karşılığı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L526',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='526 Borsada Oluşan Değer Artışları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L527',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='527 Özkaynak Yöntemi Değer Artışları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L529',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='529 Diğer Sermaye Yedekleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L540',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='540 Yasal Yedekler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L541',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='541 Statü Yedekleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L542',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='542 Olağanüstü Yedekler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L543',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='543 Maliyet Artış Fonu'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L548',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='548 Diğer Kar Yedekleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L549',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='549 Özel Fonlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L551',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='551 İndirimler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L560',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='560 Ana Ortaklık Dışı Özvarlık (Azınlık Payları)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L561',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='561 Ana Ortaklık Dışı Özvarlık (Azınlık Payları)(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L562',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='562 Çevrim Farkları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L563',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='563 Çevrim Farkları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L570',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='570 Geçmiş Yıllar Karları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L580',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='580 Geçmiş Yıllar Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L590',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='590 Dönem Net Karı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L591',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='591 Dönem Net Zararı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L600',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='600 Yurtiçi Satışlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L601',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='601 Yurtdışı Satışlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L602',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='602 Diğer Gelirler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L603',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='603 Yurtiçi Biten İşler Geliri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L604',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='604 Yurtdışı Biten İşler Geliri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L610',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='610 Satıştan İadeler(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L611',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='611 Satış İskontoları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L612',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='612 Diğer İndirimler'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L620',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='620 Satılan Mamuller Maliyeti(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L621',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='621 Satılan Ticari Mallar Maliyeti(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L622',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='622 Satılan Hizmet Maliyeti(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L623',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='623 Diğer Satışların Maliyeti'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L624',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='624 Hammadde ve Malzeme Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L625',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='625 Dolaysız İşçilik Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L626',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='626 Genel Üretim Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L627',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='627 Yarı Mamul Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L628',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='628 Amortismanlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L630',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='630 AR-GE Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L631',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='631 Pazarlama, Satış, Dağıtım Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L632',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='632 Genele Yönetim Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L633',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='633 Diğer'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L634',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='634 Amortismanlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L640',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='640 İştiraklerden Temettü Gelirleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L641',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='641 Bağlı Ortaklıklardan Temettü Gelirleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L642',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='642 Faiz Gelirleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L643',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='643 Komisyon Gelirleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L644',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='644 Konusu Kalmayan Karşılıklar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L645',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='645 Menkul Kıymet Satış Karları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L646',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='646 Kambiyo Karları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L647',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='647 Reeskont Faiz Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L648',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='648 Enflasyon Düzeltmesi Karları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L649',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='649 Diğer Olağan Gelir ve Karlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L653',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='653 Komisyon Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L654',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='654 Karşılık Giderleri'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L655',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='655 Menkul Kıymet Satış Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L656',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='656 Kambiyo Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L657',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='657 Reeskont Faiz Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L658',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='658 Enflasyon Düzeltmesi Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L659',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='659 Diğer Gider ve Zararlar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L660',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='660 Kısa Vadeli Borçlanma Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L661',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='661 Uzun Vadeli Borçlanma Giderleri(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L671',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='671 Önceki Dönem Gelir ve Karları'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L677',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='677 Net Parasal Pozisyon Karı'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L678',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='678 Ana Ortaklık Dışı Kar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L679',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='679 Diğer Olağandışı Gelir ve Karlar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L680',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='680 Çalışmayan Kısım Gider ve Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L681',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='681 Önceki Dönem Gider ve Zararları(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L687',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='687 Net Parasal Pozisyon Zararı(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L688',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='688 Ana Ortaklık Dışı Zarar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L689',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='689 Diğer Olağandışı Gider ve Zararlar(-)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='L690',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='691 Dönem Karı Vergi ve Diğer Yas. Yük. Karş.'),
        ),
    ]
