# Generated by Django 3.0.4 on 2020-04-24 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı / (Kayıtlı kullanıcı değilseniz Ad Soyad giriniz)')),
                ('email', models.EmailField(max_length=50, verbose_name='e-posta adresiniz')),
                ('title', models.CharField(max_length=300, verbose_name='Mesaj Konusu (Mesajınız ne ile ilgili?)')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mesaj İçeriği')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Konuya ilişkin eklemek istediğiniz belge varsa ekleyin')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
