
from budget.mizan import M
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.utils.text import slugify


class Budget(models.Model):
    user = models.ForeignKey('auth.User', verbose_name='Kullanıcı', on_delete=models.CASCADE, related_name='budgets')
    period = models.DateField(verbose_name='Mali Dönem')
    tax_number = models.CharField(max_length=11, verbose_name='Firma Vergi Numarası')
    tax_title = models.CharField(max_length=100, verbose_name='Firma Ünvanı')
    grup_ismi = models.CharField(max_length=50, blank=True, verbose_name='Grup firmaları varsa grubun adını girin')
    # Aktif Dönen Varlık
    L100 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["100"])
    L101 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["101"])
    L102 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["102"])
    L103 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["103"])
    L108 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["108"])
    L110 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["110"])
    L111 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["111"])
    L112 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["112"])
    L118 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["118"])
    L119 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["119"])
    L1201 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["1201"])
    L1202 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["1202"])
    L1203 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["1203"])
    L121 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["121"])
    L122 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["122"])
    L126 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["126"])
    L127 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["127"])
    L128 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["128"])
    L129 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["129"])
    L131 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["131"])
    L132 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["132"])
    L133 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["133"])
    L135 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["135"])
    L136 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["136"])
    L137 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["137"])
    L138 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["138"])
    L139 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["139"])
    L150 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["150"])
    L151 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["151"])
    L152 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["152"])
    L153 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["153"])
    L157 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["157"])
    L158 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["158"])
    L159 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["159"])
    L170 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["170"])
    L171 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["171"])
    L178 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["178"])
    L180 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["180"])
    L181 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["181"])
    L190 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["190"])
    L191 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["191"])
    L192 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["192"])
    L193 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["193"])
    L194 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["194"])
    L196 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["196"])
    L195 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["195"])
    L197 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["197"])
    L198 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["198"])
    L199 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["199"])
    #  Aktif Duran Varlık
    L200 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["200"])
    L201 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["201"])
    L210 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["210"])
    L211 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["211"])
    L2201 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["2201"])
    L2202 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["2202"])
    L221 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["221"])
    L222 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["222"])
    L226 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["226"])
    L228 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["228"])
    L229 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["229"])
    L231 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["231"])
    L232 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["232"])
    L233 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["233"])
    L235 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["235"])
    L236 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["236"])
    L237 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["237"])
    L239 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["239"])
    L240 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["240"])
    L241 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["241"])
    L242 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["242"])
    L243 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["243"])
    L244 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["244"])
    L245 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["245"])
    L246 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["246"])
    L247 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["247"])
    L248 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["248"])
    L249 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["249"])
    L250 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["250"])
    L251 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["251"])
    L252 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["252"])
    L253 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["253"])
    L254 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["254"])
    L255 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["255"])
    L256 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["256"])
    L257 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["257"])
    L258 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["258"])
    L259 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["259"])
    L260 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["260"])
    L261 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["261"])
    L262 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["262"])
    L263 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["263"])
    L264 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["264"])
    L267 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["267"])
    L268 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["268"])
    L269 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["269"])
    L271 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["271"])
    L272 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["272"])
    L277 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["277"])
    L278 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["278"])
    L279 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["279"])
    L280 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["280"])
    L281 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["281"])
    L291 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["291"])
    L292 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["292"])
    L293 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["293"])
    L294 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["294"])
    L295 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["295"])
    L296 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["296"])
    L297 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["297"])
    L298 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["298"])
    L299 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["299"])
    # Pasif Kısa Vade
    L300 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["300"])
    L301 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["301"])
    L302 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["302"])
    L303 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["303"])
    L304 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["304"])
    L305 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["305"])
    L306 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["306"])
    L308 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["308"])
    L309 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["309"])
    L3201 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["3201"])
    L3202 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["3202"])
    L321 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["321"])
    L322 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["322"])
    L326 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["326"])
    L329 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["329"])
    L331 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["331"])
    L332 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["332"])
    L333 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["333"])
    L335 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["335"])
    L336 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["336"])
    L337 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["337"])
    L338 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["338"])
    L340 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["340"])
    L349 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["349"])
    L350 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["350"])
    L351 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["351"])
    L358 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["358"])
    L360 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["360"])
    L361 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["361"])
    L368 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["368"])
    L369 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["369"])
    L370 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["370"])
    L371 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["371"])
    L372 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["372"])
    L373 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["373"])
    L379 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["379"])
    L380 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["380"])
    L381 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["381"])
    L391 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["391"])
    L392 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["392"])
    L393 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["393"])
    L394 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["394"])
    L397 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["397"])
    L399 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["399"])
    # Pasif Uzun Vade
    L400 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["400"])
    L401 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["401"])
    L402 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["402"])
    L405 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["405"])
    L407 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["407"])
    L408 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["408"])
    L409 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["409"])
    L410 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["410"])
    L420 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["420"])
    L421 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["421"])
    L422 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["422"])
    L426 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["426"])
    L429 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["429"])
    L431 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["431"])
    L432 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["432"])
    L433 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["433"])
    L436 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["436"])
    L437 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["437"])
    L438 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["438"])
    L440 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["440"])
    L449 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["449"])
    L472 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["472"])
    L479 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["479"])
    L480 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["480"])
    L481 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["481"])
    L492 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["492"])
    L493 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["493"])
    L496 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["496"])
    L499 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["499"])
    # Pasif Özkaynak
    L500 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["500"])
    L501 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["501"])
    L502 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["502"])
    L503 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["503"])
    L520 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["520"])
    L521 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["521"])
    L522 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["522"])
    L523 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["523"])
    L525 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["525"])
    L526 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["526"])
    L527 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["527"])
    L529 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["529"])
    L540 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["540"])
    L541 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["541"])
    L542 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["542"])
    L543 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["543"])
    L548 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["548"])
    L549 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["549"])
    L551 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["551"])
    L560 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["560"])
    L561 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["561"])
    L562 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["562"])
    L563 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["563"])
    L570 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["570"])
    L580 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["580"])
    L590 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["590"])
    L591 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["591"])
    # Gelir Tablosu
    L600 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["600"])
    L601 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["601"])
    L602 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["602"])
    L603 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["603"])
    L604 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["604"])
    L610 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["610"])
    L611 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["611"])
    L612 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["612"])
    L620 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["620"])
    L621 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["621"])
    L622 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["622"])
    L623 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["623"])
    L624 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["624"])
    L625 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["625"])
    L626 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["626"])
    L627 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["627"])
    L628 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["628"])
    L630 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["630"])
    L631 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["631"])
    L632 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["632"])
    L633 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["633"])
    L634 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["634"])
    L640 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["640"])
    L641 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["641"])
    L642 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["642"])
    L643 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["643"])
    L644 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["644"])
    L645 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["645"])
    L646 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["646"])
    L647 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["647"])
    L648 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["648"])
    L649 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["649"])
    L653 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["653"])
    L654 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["654"])
    L655 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["655"])
    L656 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["656"])
    L657 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["657"])
    L658 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["658"])
    L659 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["659"])
    L660 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["660"])
    L661 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["661"])
    L671 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["671"])
    L677 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["677"])
    L678 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["678"])
    L679 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["679"])
    L680 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["680"])
    L681 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["681"])
    L687 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["687"])
    L688 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["688"])
    L689 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["689"])
    L690 = models.DecimalField(default=0, decimal_places=2, max_digits=20, verbose_name=M["690"])

    company = RichTextField(blank=True, verbose_name='Firmaya / Gruba ve faaliyetlerine ilişkin açıklamalar:')
    comment1 = RichTextField(blank=True, verbose_name='Dönen Varlık Kalemlerine İlişkin Tespitler ve Yorumlar:')
    comment2 = RichTextField(blank=True, verbose_name='Duran Varlık Kalemlerine İlişkin Tespitler ve Yorumlar:')
    comment3 = RichTextField(blank=True, verbose_name='Yabancı Kaynaklar Kalemlerine İlişkin Tespitler ve Yorumlar:')
    comment4 = RichTextField(blank=True, verbose_name='Özkaynak Kalemlerine İlişkin Tespitler ve Yorumlar:')
    comment5 = RichTextField(blank=True, verbose_name='Gelir Tablosuna İlişkin Tespitler ve Yorumlar:')
    comment6 = RichTextField(blank=True, verbose_name='Oran Analizine İlişkin Tespitler ve Yorumlar:')
    comments = RichTextField(blank=True, verbose_name='Mali Verilere / Mali Duruma İlişkin Yorumlar:')
    advice = RichTextField(blank=True, verbose_name='Firmaya / Gruba tavsiyeleriniz nedir:')

    rate = models.DecimalField(null=True, blank=True, default=0, decimal_places=2, max_digits=6, verbose_name='Dönem Notu:')
    company_rate = models.DecimalField(null=True, blank=True, default=0, decimal_places=2, max_digits=6, verbose_name='Firma Notu:')
    group_rate = models.DecimalField(null=True, blank=True, default=0, decimal_places=2, max_digits=6, verbose_name='Grup Notu:')

    saving_date = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')
    files = models.FileField(null=True, blank=True, verbose_name='Varsa Mali Döneme İlişkin Dosya Ekleyin:')

    def __str__(self):
        return self.tax_title

    def get_absolute_url(self):
        return reverse('budget:detail', kwargs={'id': self.id})

    def get_basetable_url(self):
        return reverse('budget:basetable', kwargs={'id': self.id})

    def get_create_url(self):
        return reverse('budget:create')  # ama yeni nesne üreteceği için mevcut bir id vermeye gerek yok

    def get_update_url(self):
        return reverse('budget:update', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('budget:delete', kwargs={'id': self.id})

    def get_lists_url(self):
        return reverse('budget:lists', kwargs={'vergi': self.tax_number})

    def get_spread_url(self):
        return reverse('budget:spread', kwargs={'id': self.id})

    def get_compare_url(self):
        return reverse('budget:compare', kwargs={'vergi': self.tax_number})

    def get_group_url(self):
        return reverse('budget:grouplist', kwargs={'id': self.id})

    def get_groupspread_url(self):
        if self.grup_ismi:
            return reverse('budget:groupspread', kwargs={'slug': slugify(self.grup_ismi)})
        else:
            return reverse('budget:grouplist', kwargs={'id': self.id})

    def get_groupfirms_url(self):
        if self.grup_ismi:
            return reverse('budget:groupfirms', kwargs={'slug': slugify(self.grup_ismi)})
        else:
            return reverse('budget:groups')

    def get_analysis_url(self):
        return reverse('budget:analysis', kwargs={'id': self.id})

    def get_report_url(self):
        # if self.grup_ismi:
        #     return reverse('budget:report', kwargs={'slug': slugify(self.grup_ismi), 'id': self.id})
        # else:
        return reverse('budget:report', kwargs={'id': self.id})

    def get_pdf_url(self):
        return reverse('budget:pdf', kwargs={'id': self.id})

    class Meta:
        ordering = ['user', 'tax_title', '-period', '-saving_date', 'id']
