# Generated by Django 3.0.4 on 2020-06-08 08:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0003_auto_20200515_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='button',
            field=models.CharField(blank=True, max_length=30, verbose_name='Butonun Yazısı'),
        ),
        migrations.AddField(
            model_name='haber',
            name='konum',
            field=models.CharField(blank=True, choices=[('S', 'CAROUSEL-SLİDER'), ('M', 'MARKETING'), ('F', 'FEATURETTE'), ('H', 'HAKKIMIZDA')], max_length=20, verbose_name='Konumunu Seçin'),
        ),
        migrations.AddField(
            model_name='haber',
            name='position',
            field=models.IntegerField(blank=True, default=0, verbose_name='Yerleşim Sırası Seçin (0 ile başlar)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='haber',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Haber İçeriği'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Haber Altbaşlığı'),
        ),
    ]
