# Generated by Django 3.0.4 on 2020-06-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0004_auto_20200608_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haber',
            options={'ordering': ['-konum', 'position']},
        ),
    ]
